version: "3.7"

services:
  app:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./:/app
  mysql:
    image: mysql:8.0.31
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jd_workout
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  lint:
    image: golangci/golangci-lint:v1.52.2
    volumes:
      - .:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
volumes:
  mysql_data:
