name: CI

on:
  push:
    branches:
      - test-branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test
        run: |
          echo "ci time: $(date)" >> /app/ci-log && tail /app/ci-log