name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tags'
        required: true
      commitish:
        description: 'branch or commit id'
        required: true
        default: 'master'
      project_column:
        description: 'project_column'
        required: true
        default: 'stage'
jobs:
  build:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: get-body
        env:
          PROJECT_COLUMN: ${{ github.event.inputs.project_column }}
        with:
          result-encoding: string
          script: |
            let str = 'test aaavvv\n';
            
            str .= '依「系統安全要求檢查表」的適用項目 9、10.1 進行安全性評估後，此次的調整並無安全性疑慮。';
            
            return str
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: regular release
          commitish: ${{ github.event.inputs.commitish }}
          body: ${{ steps.get-body.outputs.result }}
          draft: true
          prerelease: true