name: Update Release Notes-2

on:
  release:
    types: [published, unpublished]

jobs:
  update-release-notes:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Update Release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let updatedNote = context.payload.release.body;
            console.log("updatedNote....aaaaaaaaa");
            console.log(updatedNote);

            updatedNote += "\n\n\n\n auto add zz1234";
            
            github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: updatedNote
            });
